/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_window_etudiant (void);
GtkWidget* create_window_admin (void);
GtkWidget* create_window_capteur (void);
GtkWidget* create_window_nutritionniste (void);
GtkWidget* create_window_stock (void);
GtkWidget* create_window_reclamation (void);
GtkWidget* create_window_etudiant_ajouter (void);
GtkWidget* create_window_etudiant_modifier (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_choisir (void);
GtkWidget* create_ajoutreclamation (void);
GtkWidget* create_affichreclamation (void);
GtkWidget* create_supprec (void);
GtkWidget* create_modifrecher (void);
GtkWidget* create_sure (void);
GtkWidget* create_serviceplusreclame (void);
GtkWidget* create_diag (void);
GtkWidget* create_window_modif (void);
GtkWidget* create_window_rech (void);
GtkWidget* create_window_def (void);
GtkWidget* create_tech (void);
GtkWidget* create_window1menu (void);
GtkWidget* create_window2_ajout (void);
GtkWidget* create_window33 (void);
GtkWidget* create_window5meilleur (void);
GtkWidget* create_windowmodifier (void);
GtkWidget* create_menu (void);
GtkWidget* create_ajout_stock (void);
GtkWidget* create_modif_stock (void);
GtkWidget* create_recherche_stock (void);
GtkWidget* create_verif (void);
GtkWidget* create_cherche (void);
GtkWidget* create_dash (void);
GtkWidget* create_Gestion (void);
GtkWidget* create_ajout_modif (void);
GtkWidget* create_Dashboard (void);
GtkWidget* create_re (void);
GtkWidget* create_DELETE (void);
GtkWidget* create_ichraktache2 (void);
GtkWidget* create_tous (void);
